/* 
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Cpayment.Connector.Client.OpenAPIDateConverter;

namespace Cpayment.Connector.Model
{
    /// <summary>
    /// The validate authentication request.
    /// </summary>
    [DataContract]
    public partial class Card3DsValidateAuthenticationRequest :  IEquatable<Card3DsValidateAuthenticationRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Card3DsValidateAuthenticationRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Card3DsValidateAuthenticationRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Card3DsValidateAuthenticationRequest" /> class.
        /// </summary>
        /// <param name="merchantId">The merchant identifier (required).</param>
        /// <param name="merchantSiteId">The merchant site identifier (required).</param>
        /// <param name="card3dsPaymentRequestId">The payment session identifier (guid), use it for 3DS payment (required).</param>
        /// <param name="orderRef">The order reference linked to the schedule and transaction (required).</param>
        /// <param name="orderTag">The order tag is a label for the schedule.</param>
        public Card3DsValidateAuthenticationRequest(int? merchantId = default(int?), string merchantSiteId = default(string), string card3dsPaymentRequestId = default(string), string orderRef = default(string), string orderTag = default(string))
        {
            // to ensure "merchantId" is required (not null)
            if (merchantId == null)
            {
                throw new InvalidDataException("merchantId is a required property for Card3DsValidateAuthenticationRequest and cannot be null");
            }
            else
            {
                this.MerchantId = merchantId;
            }
            
            // to ensure "merchantSiteId" is required (not null)
            if (merchantSiteId == null)
            {
                throw new InvalidDataException("merchantSiteId is a required property for Card3DsValidateAuthenticationRequest and cannot be null");
            }
            else
            {
                this.MerchantSiteId = merchantSiteId;
            }
            
            // to ensure "card3dsPaymentRequestId" is required (not null)
            if (card3dsPaymentRequestId == null)
            {
                throw new InvalidDataException("card3dsPaymentRequestId is a required property for Card3DsValidateAuthenticationRequest and cannot be null");
            }
            else
            {
                this.Card3dsPaymentRequestId = card3dsPaymentRequestId;
            }
            
            // to ensure "orderRef" is required (not null)
            if (orderRef == null)
            {
                throw new InvalidDataException("orderRef is a required property for Card3DsValidateAuthenticationRequest and cannot be null");
            }
            else
            {
                this.OrderRef = orderRef;
            }
            
            this.OrderTag = orderTag;
        }
        
        /// <summary>
        /// The merchant identifier
        /// </summary>
        /// <value>The merchant identifier</value>
        [DataMember(Name="merchantId", EmitDefaultValue=false)]
        public int? MerchantId { get; set; }

        /// <summary>
        /// The merchant site identifier
        /// </summary>
        /// <value>The merchant site identifier</value>
        [DataMember(Name="merchantSiteId", EmitDefaultValue=false)]
        public string MerchantSiteId { get; set; }

        /// <summary>
        /// The payment session identifier (guid), use it for 3DS payment
        /// </summary>
        /// <value>The payment session identifier (guid), use it for 3DS payment</value>
        [DataMember(Name="card3dsPaymentRequestId", EmitDefaultValue=false)]
        public string Card3dsPaymentRequestId { get; set; }

        /// <summary>
        /// The order reference linked to the schedule and transaction
        /// </summary>
        /// <value>The order reference linked to the schedule and transaction</value>
        [DataMember(Name="orderRef", EmitDefaultValue=false)]
        public string OrderRef { get; set; }

        /// <summary>
        /// The order tag is a label for the schedule
        /// </summary>
        /// <value>The order tag is a label for the schedule</value>
        [DataMember(Name="orderTag", EmitDefaultValue=false)]
        public string OrderTag { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Card3DsValidateAuthenticationRequest {\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  MerchantSiteId: ").Append(MerchantSiteId).Append("\n");
            sb.Append("  Card3dsPaymentRequestId: ").Append(Card3dsPaymentRequestId).Append("\n");
            sb.Append("  OrderRef: ").Append(OrderRef).Append("\n");
            sb.Append("  OrderTag: ").Append(OrderTag).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Card3DsValidateAuthenticationRequest);
        }

        /// <summary>
        /// Returns true if Card3DsValidateAuthenticationRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of Card3DsValidateAuthenticationRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Card3DsValidateAuthenticationRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MerchantId == input.MerchantId ||
                    (this.MerchantId != null &&
                    this.MerchantId.Equals(input.MerchantId))
                ) && 
                (
                    this.MerchantSiteId == input.MerchantSiteId ||
                    (this.MerchantSiteId != null &&
                    this.MerchantSiteId.Equals(input.MerchantSiteId))
                ) && 
                (
                    this.Card3dsPaymentRequestId == input.Card3dsPaymentRequestId ||
                    (this.Card3dsPaymentRequestId != null &&
                    this.Card3dsPaymentRequestId.Equals(input.Card3dsPaymentRequestId))
                ) && 
                (
                    this.OrderRef == input.OrderRef ||
                    (this.OrderRef != null &&
                    this.OrderRef.Equals(input.OrderRef))
                ) && 
                (
                    this.OrderTag == input.OrderTag ||
                    (this.OrderTag != null &&
                    this.OrderTag.Equals(input.OrderTag))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MerchantId != null)
                    hashCode = hashCode * 59 + this.MerchantId.GetHashCode();
                if (this.MerchantSiteId != null)
                    hashCode = hashCode * 59 + this.MerchantSiteId.GetHashCode();
                if (this.Card3dsPaymentRequestId != null)
                    hashCode = hashCode * 59 + this.Card3dsPaymentRequestId.GetHashCode();
                if (this.OrderRef != null)
                    hashCode = hashCode * 59 + this.OrderRef.GetHashCode();
                if (this.OrderTag != null)
                    hashCode = hashCode * 59 + this.OrderTag.GetHashCode();
                return hashCode;
            }
        }
    }

}
