/* 
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Cpayment.Connector.Client.OpenAPIDateConverter;

namespace Cpayment.Connector.Model
{
    /// <summary>
    /// All payment operation data for the response
    /// </summary>
    [DataContract]
    public partial class PaymentOperationsResponse :  IEquatable<PaymentOperationsResponse>
    {
        /// <summary>
        /// The response code of the service
        /// </summary>
        /// <value>The response code of the service</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ResponseCodeEnum
        {
            /// <summary>
            /// Enum Undetermined for value: undetermined
            /// </summary>
            [EnumMember(Value = "undetermined")]
            Undetermined = 1,

            /// <summary>
            /// Enum Success for value: success
            /// </summary>
            [EnumMember(Value = "success")]
            Success = 2,

            /// <summary>
            /// Enum Refused for value: refused
            /// </summary>
            [EnumMember(Value = "refused")]
            Refused = 3,

            /// <summary>
            /// Enum RefusedByBank for value: refusedByBank
            /// </summary>
            [EnumMember(Value = "refusedByBank")]
            RefusedByBank = 4,

            /// <summary>
            /// Enum InternalFailure for value: internalFailure
            /// </summary>
            [EnumMember(Value = "internalFailure")]
            InternalFailure = 5,

            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 6,

            /// <summary>
            /// Enum Unavailable for value: unavailable
            /// </summary>
            [EnumMember(Value = "unavailable")]
            Unavailable = 7

        }

        /// <summary>
        /// The response code of the service
        /// </summary>
        /// <value>The response code of the service</value>
        [DataMember(Name="responseCode", EmitDefaultValue=false)]
        public ResponseCodeEnum? ResponseCode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentOperationsResponse" /> class.
        /// </summary>
        /// <param name="orderTag">The orderTag.</param>
        /// <param name="schedules">All schedules data.</param>
        /// <param name="orderRef">The orderRef.</param>
        /// <param name="responseCode">The response code of the service.</param>
        /// <param name="actionType">The action type.</param>
        /// <param name="responseMessage">The global response message.</param>
        public PaymentOperationsResponse(string orderTag = default(string), List<Schedule> schedules = default(List<Schedule>), string orderRef = default(string), ResponseCodeEnum? responseCode = default(ResponseCodeEnum?), string actionType = default(string), string responseMessage = default(string))
        {
            this.OrderTag = orderTag;
            this.Schedules = schedules;
            this.OrderRef = orderRef;
            this.ResponseCode = responseCode;
            this.ActionType = actionType;
            this.ResponseMessage = responseMessage;
        }
        
        /// <summary>
        /// The orderTag
        /// </summary>
        /// <value>The orderTag</value>
        [DataMember(Name="orderTag", EmitDefaultValue=false)]
        public string OrderTag { get; set; }

        /// <summary>
        /// All schedules data
        /// </summary>
        /// <value>All schedules data</value>
        [DataMember(Name="schedules", EmitDefaultValue=false)]
        public List<Schedule> Schedules { get; set; }

        /// <summary>
        /// The orderRef
        /// </summary>
        /// <value>The orderRef</value>
        [DataMember(Name="orderRef", EmitDefaultValue=false)]
        public string OrderRef { get; set; }


        /// <summary>
        /// The action type
        /// </summary>
        /// <value>The action type</value>
        [DataMember(Name="actionType", EmitDefaultValue=false)]
        public string ActionType { get; set; }

        /// <summary>
        /// The global response message
        /// </summary>
        /// <value>The global response message</value>
        [DataMember(Name="responseMessage", EmitDefaultValue=false)]
        public string ResponseMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentOperationsResponse {\n");
            sb.Append("  OrderTag: ").Append(OrderTag).Append("\n");
            sb.Append("  Schedules: ").Append(Schedules).Append("\n");
            sb.Append("  OrderRef: ").Append(OrderRef).Append("\n");
            sb.Append("  ResponseCode: ").Append(ResponseCode).Append("\n");
            sb.Append("  ActionType: ").Append(ActionType).Append("\n");
            sb.Append("  ResponseMessage: ").Append(ResponseMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentOperationsResponse);
        }

        /// <summary>
        /// Returns true if PaymentOperationsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentOperationsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentOperationsResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OrderTag == input.OrderTag ||
                    (this.OrderTag != null &&
                    this.OrderTag.Equals(input.OrderTag))
                ) && 
                (
                    this.Schedules == input.Schedules ||
                    this.Schedules != null &&
                    input.Schedules != null &&
                    this.Schedules.SequenceEqual(input.Schedules)
                ) && 
                (
                    this.OrderRef == input.OrderRef ||
                    (this.OrderRef != null &&
                    this.OrderRef.Equals(input.OrderRef))
                ) && 
                (
                    this.ResponseCode == input.ResponseCode ||
                    (this.ResponseCode != null &&
                    this.ResponseCode.Equals(input.ResponseCode))
                ) && 
                (
                    this.ActionType == input.ActionType ||
                    (this.ActionType != null &&
                    this.ActionType.Equals(input.ActionType))
                ) && 
                (
                    this.ResponseMessage == input.ResponseMessage ||
                    (this.ResponseMessage != null &&
                    this.ResponseMessage.Equals(input.ResponseMessage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OrderTag != null)
                    hashCode = hashCode * 59 + this.OrderTag.GetHashCode();
                if (this.Schedules != null)
                    hashCode = hashCode * 59 + this.Schedules.GetHashCode();
                if (this.OrderRef != null)
                    hashCode = hashCode * 59 + this.OrderRef.GetHashCode();
                if (this.ResponseCode != null)
                    hashCode = hashCode * 59 + this.ResponseCode.GetHashCode();
                if (this.ActionType != null)
                    hashCode = hashCode * 59 + this.ActionType.GetHashCode();
                if (this.ResponseMessage != null)
                    hashCode = hashCode * 59 + this.ResponseMessage.GetHashCode();
                return hashCode;
            }
        }
    }

}
