/* 
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using pachirapay.Connector.Client;
using pachirapay.Connector.Model;

namespace pachirapay.Connector.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStoredPaymentMethodsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets stored payment methods by CustomerRef
        /// </summary>
        /// <remarks>
        /// Gets the stored payment methods by customer reference.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier.</param>
        /// <param name="merchantSiteId">The merchant site identifier.</param>
        /// <param name="customerRef">The customer reference.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>StoredPaymentMethodResponse</returns>
        StoredPaymentMethodResponse V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet (int? merchantId, string merchantSiteId, string customerRef, string authToken);

        /// <summary>
        /// Gets stored payment methods by CustomerRef
        /// </summary>
        /// <remarks>
        /// Gets the stored payment methods by customer reference.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier.</param>
        /// <param name="merchantSiteId">The merchant site identifier.</param>
        /// <param name="customerRef">The customer reference.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>ApiResponse of StoredPaymentMethodResponse</returns>
        ApiResponse<StoredPaymentMethodResponse> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGetWithHttpInfo (int? merchantId, string merchantSiteId, string customerRef, string authToken);
        /// <summary>
        /// Deletes a stored payment method
        /// </summary>
        /// <remarks>
        /// Deletes the specified stored payment method.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier</param>
        /// <param name="merchantSiteId">The merchant site identifier</param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>string</returns>
        string V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken);

        /// <summary>
        /// Deletes a stored payment method
        /// </summary>
        /// <remarks>
        /// Deletes the specified stored payment method.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier</param>
        /// <param name="merchantSiteId">The merchant site identifier</param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDeleteWithHttpInfo (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken);
        /// <summary>
        /// Gets a stored payment method
        /// </summary>
        /// <remarks>
        /// Gets the stored payment method by its unique identifier.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="merchantSiteId"></param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>StoredPaymentMethodResponse</returns>
        StoredPaymentMethodResponse V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken);

        /// <summary>
        /// Gets a stored payment method
        /// </summary>
        /// <remarks>
        /// Gets the stored payment method by its unique identifier.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="merchantSiteId"></param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>ApiResponse of StoredPaymentMethodResponse</returns>
        ApiResponse<StoredPaymentMethodResponse> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGetWithHttpInfo (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken);
        /// <summary>
        /// Stores a new payment method.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <param name="storedPaymentMethodRequest">The payment method to store. (optional)</param>
        /// <returns>string</returns>
        string V1StoredPaymentMethodsPost (string authToken, StoredPaymentMethodRequest storedPaymentMethodRequest = null);

        /// <summary>
        /// Stores a new payment method.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <param name="storedPaymentMethodRequest">The payment method to store. (optional)</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> V1StoredPaymentMethodsPostWithHttpInfo (string authToken, StoredPaymentMethodRequest storedPaymentMethodRequest = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Gets stored payment methods by CustomerRef
        /// </summary>
        /// <remarks>
        /// Gets the stored payment methods by customer reference.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier.</param>
        /// <param name="merchantSiteId">The merchant site identifier.</param>
        /// <param name="customerRef">The customer reference.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of StoredPaymentMethodResponse</returns>
        System.Threading.Tasks.Task<StoredPaymentMethodResponse> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGetAsync (int? merchantId, string merchantSiteId, string customerRef, string authToken);

        /// <summary>
        /// Gets stored payment methods by CustomerRef
        /// </summary>
        /// <remarks>
        /// Gets the stored payment methods by customer reference.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier.</param>
        /// <param name="merchantSiteId">The merchant site identifier.</param>
        /// <param name="customerRef">The customer reference.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of ApiResponse (StoredPaymentMethodResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<StoredPaymentMethodResponse>> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGetAsyncWithHttpInfo (int? merchantId, string merchantSiteId, string customerRef, string authToken);
        /// <summary>
        /// Deletes a stored payment method
        /// </summary>
        /// <remarks>
        /// Deletes the specified stored payment method.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier</param>
        /// <param name="merchantSiteId">The merchant site identifier</param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDeleteAsync (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken);

        /// <summary>
        /// Deletes a stored payment method
        /// </summary>
        /// <remarks>
        /// Deletes the specified stored payment method.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier</param>
        /// <param name="merchantSiteId">The merchant site identifier</param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDeleteAsyncWithHttpInfo (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken);
        /// <summary>
        /// Gets a stored payment method
        /// </summary>
        /// <remarks>
        /// Gets the stored payment method by its unique identifier.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="merchantSiteId"></param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of StoredPaymentMethodResponse</returns>
        System.Threading.Tasks.Task<StoredPaymentMethodResponse> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGetAsync (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken);

        /// <summary>
        /// Gets a stored payment method
        /// </summary>
        /// <remarks>
        /// Gets the stored payment method by its unique identifier.
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="merchantSiteId"></param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of ApiResponse (StoredPaymentMethodResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<StoredPaymentMethodResponse>> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGetAsyncWithHttpInfo (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken);
        /// <summary>
        /// Stores a new payment method.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <param name="storedPaymentMethodRequest">The payment method to store. (optional)</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> V1StoredPaymentMethodsPostAsync (string authToken, StoredPaymentMethodRequest storedPaymentMethodRequest = null);

        /// <summary>
        /// Stores a new payment method.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <param name="storedPaymentMethodRequest">The payment method to store. (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> V1StoredPaymentMethodsPostAsyncWithHttpInfo (string authToken, StoredPaymentMethodRequest storedPaymentMethodRequest = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StoredPaymentMethodsApi : IStoredPaymentMethodsApi
    {
        private pachirapay.Connector.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StoredPaymentMethodsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StoredPaymentMethodsApi(String basePath)
        {
            this.Configuration = new pachirapay.Connector.Client.Configuration { BasePath = basePath };

            ExceptionFactory = pachirapay.Connector.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StoredPaymentMethodsApi"/> class
        /// </summary>
        /// <returns></returns>
        public StoredPaymentMethodsApi()
        {
            this.Configuration = pachirapay.Connector.Client.Configuration.Default;

            ExceptionFactory = pachirapay.Connector.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StoredPaymentMethodsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StoredPaymentMethodsApi(pachirapay.Connector.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = pachirapay.Connector.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = pachirapay.Connector.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public pachirapay.Connector.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public pachirapay.Connector.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Gets stored payment methods by CustomerRef Gets the stored payment methods by customer reference.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier.</param>
        /// <param name="merchantSiteId">The merchant site identifier.</param>
        /// <param name="customerRef">The customer reference.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>StoredPaymentMethodResponse</returns>
        public StoredPaymentMethodResponse V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet (int? merchantId, string merchantSiteId, string customerRef, string authToken)
        {
             ApiResponse<StoredPaymentMethodResponse> localVarResponse = V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGetWithHttpInfo(merchantId, merchantSiteId, customerRef, authToken);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets stored payment methods by CustomerRef Gets the stored payment methods by customer reference.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier.</param>
        /// <param name="merchantSiteId">The merchant site identifier.</param>
        /// <param name="customerRef">The customer reference.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>ApiResponse of StoredPaymentMethodResponse</returns>
        public ApiResponse< StoredPaymentMethodResponse > V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGetWithHttpInfo (int? merchantId, string merchantSiteId, string customerRef, string authToken)
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new ApiException(400, "Missing required parameter 'merchantId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet");
            // verify the required parameter 'merchantSiteId' is set
            if (merchantSiteId == null)
                throw new ApiException(400, "Missing required parameter 'merchantSiteId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet");
            // verify the required parameter 'customerRef' is set
            if (customerRef == null)
                throw new ApiException(400, "Missing required parameter 'customerRef' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet");
            // verify the required parameter 'authToken' is set
            if (authToken == null)
                throw new ApiException(400, "Missing required parameter 'authToken' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet");

            var localVarPath = "./v1/stored-payment-methods/merchants/{merchantId}/sites/{merchantSiteId}/customerRef/{customerRef}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (merchantId != null) localVarPathParams.Add("merchantId", this.Configuration.ApiClient.ParameterToString(merchantId)); // path parameter
            if (merchantSiteId != null) localVarPathParams.Add("merchantSiteId", this.Configuration.ApiClient.ParameterToString(merchantSiteId)); // path parameter
            if (customerRef != null) localVarPathParams.Add("customerRef", this.Configuration.ApiClient.ParameterToString(customerRef)); // path parameter
            if (authToken != null) localVarHeaderParams.Add("authToken", this.Configuration.ApiClient.ParameterToString(authToken)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StoredPaymentMethodResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StoredPaymentMethodResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StoredPaymentMethodResponse)));
        }

        /// <summary>
        /// Gets stored payment methods by CustomerRef Gets the stored payment methods by customer reference.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier.</param>
        /// <param name="merchantSiteId">The merchant site identifier.</param>
        /// <param name="customerRef">The customer reference.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of StoredPaymentMethodResponse</returns>
        public async System.Threading.Tasks.Task<StoredPaymentMethodResponse> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGetAsync (int? merchantId, string merchantSiteId, string customerRef, string authToken)
        {
             ApiResponse<StoredPaymentMethodResponse> localVarResponse = await V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGetAsyncWithHttpInfo(merchantId, merchantSiteId, customerRef, authToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets stored payment methods by CustomerRef Gets the stored payment methods by customer reference.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier.</param>
        /// <param name="merchantSiteId">The merchant site identifier.</param>
        /// <param name="customerRef">The customer reference.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of ApiResponse (StoredPaymentMethodResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StoredPaymentMethodResponse>> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGetAsyncWithHttpInfo (int? merchantId, string merchantSiteId, string customerRef, string authToken)
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new ApiException(400, "Missing required parameter 'merchantId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet");
            // verify the required parameter 'merchantSiteId' is set
            if (merchantSiteId == null)
                throw new ApiException(400, "Missing required parameter 'merchantSiteId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet");
            // verify the required parameter 'customerRef' is set
            if (customerRef == null)
                throw new ApiException(400, "Missing required parameter 'customerRef' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet");
            // verify the required parameter 'authToken' is set
            if (authToken == null)
                throw new ApiException(400, "Missing required parameter 'authToken' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet");

            var localVarPath = "./v1/stored-payment-methods/merchants/{merchantId}/sites/{merchantSiteId}/customerRef/{customerRef}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (merchantId != null) localVarPathParams.Add("merchantId", this.Configuration.ApiClient.ParameterToString(merchantId)); // path parameter
            if (merchantSiteId != null) localVarPathParams.Add("merchantSiteId", this.Configuration.ApiClient.ParameterToString(merchantSiteId)); // path parameter
            if (customerRef != null) localVarPathParams.Add("customerRef", this.Configuration.ApiClient.ParameterToString(customerRef)); // path parameter
            if (authToken != null) localVarHeaderParams.Add("authToken", this.Configuration.ApiClient.ParameterToString(authToken)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StoredPaymentMethodResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StoredPaymentMethodResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StoredPaymentMethodResponse)));
        }

        /// <summary>
        /// Deletes a stored payment method Deletes the specified stored payment method.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier</param>
        /// <param name="merchantSiteId">The merchant site identifier</param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>string</returns>
        public string V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken)
        {
             ApiResponse<string> localVarResponse = V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDeleteWithHttpInfo(merchantId, merchantSiteId, storedPaymentMethodId, authToken);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Deletes a stored payment method Deletes the specified stored payment method.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier</param>
        /// <param name="merchantSiteId">The merchant site identifier</param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDeleteWithHttpInfo (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken)
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new ApiException(400, "Missing required parameter 'merchantId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete");
            // verify the required parameter 'merchantSiteId' is set
            if (merchantSiteId == null)
                throw new ApiException(400, "Missing required parameter 'merchantSiteId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete");
            // verify the required parameter 'storedPaymentMethodId' is set
            if (storedPaymentMethodId == null)
                throw new ApiException(400, "Missing required parameter 'storedPaymentMethodId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete");
            // verify the required parameter 'authToken' is set
            if (authToken == null)
                throw new ApiException(400, "Missing required parameter 'authToken' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete");

            var localVarPath = "./v1/stored-payment-methods/merchants/{merchantId}/sites/{merchantSiteId}/storedPaymentMethodId/{storedPaymentMethodId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (merchantId != null) localVarPathParams.Add("merchantId", this.Configuration.ApiClient.ParameterToString(merchantId)); // path parameter
            if (merchantSiteId != null) localVarPathParams.Add("merchantSiteId", this.Configuration.ApiClient.ParameterToString(merchantSiteId)); // path parameter
            if (storedPaymentMethodId != null) localVarPathParams.Add("storedPaymentMethodId", this.Configuration.ApiClient.ParameterToString(storedPaymentMethodId)); // path parameter
            if (authToken != null) localVarHeaderParams.Add("authToken", this.Configuration.ApiClient.ParameterToString(authToken)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Deletes a stored payment method Deletes the specified stored payment method.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier</param>
        /// <param name="merchantSiteId">The merchant site identifier</param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDeleteAsync (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken)
        {
             ApiResponse<string> localVarResponse = await V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDeleteAsyncWithHttpInfo(merchantId, merchantSiteId, storedPaymentMethodId, authToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Deletes a stored payment method Deletes the specified stored payment method.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The merchant identifier</param>
        /// <param name="merchantSiteId">The merchant site identifier</param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDeleteAsyncWithHttpInfo (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken)
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new ApiException(400, "Missing required parameter 'merchantId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete");
            // verify the required parameter 'merchantSiteId' is set
            if (merchantSiteId == null)
                throw new ApiException(400, "Missing required parameter 'merchantSiteId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete");
            // verify the required parameter 'storedPaymentMethodId' is set
            if (storedPaymentMethodId == null)
                throw new ApiException(400, "Missing required parameter 'storedPaymentMethodId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete");
            // verify the required parameter 'authToken' is set
            if (authToken == null)
                throw new ApiException(400, "Missing required parameter 'authToken' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete");

            var localVarPath = "./v1/stored-payment-methods/merchants/{merchantId}/sites/{merchantSiteId}/storedPaymentMethodId/{storedPaymentMethodId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (merchantId != null) localVarPathParams.Add("merchantId", this.Configuration.ApiClient.ParameterToString(merchantId)); // path parameter
            if (merchantSiteId != null) localVarPathParams.Add("merchantSiteId", this.Configuration.ApiClient.ParameterToString(merchantSiteId)); // path parameter
            if (storedPaymentMethodId != null) localVarPathParams.Add("storedPaymentMethodId", this.Configuration.ApiClient.ParameterToString(storedPaymentMethodId)); // path parameter
            if (authToken != null) localVarHeaderParams.Add("authToken", this.Configuration.ApiClient.ParameterToString(authToken)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Gets a stored payment method Gets the stored payment method by its unique identifier.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="merchantSiteId"></param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>StoredPaymentMethodResponse</returns>
        public StoredPaymentMethodResponse V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken)
        {
             ApiResponse<StoredPaymentMethodResponse> localVarResponse = V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGetWithHttpInfo(merchantId, merchantSiteId, storedPaymentMethodId, authToken);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a stored payment method Gets the stored payment method by its unique identifier.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="merchantSiteId"></param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>ApiResponse of StoredPaymentMethodResponse</returns>
        public ApiResponse< StoredPaymentMethodResponse > V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGetWithHttpInfo (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken)
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new ApiException(400, "Missing required parameter 'merchantId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet");
            // verify the required parameter 'merchantSiteId' is set
            if (merchantSiteId == null)
                throw new ApiException(400, "Missing required parameter 'merchantSiteId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet");
            // verify the required parameter 'storedPaymentMethodId' is set
            if (storedPaymentMethodId == null)
                throw new ApiException(400, "Missing required parameter 'storedPaymentMethodId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet");
            // verify the required parameter 'authToken' is set
            if (authToken == null)
                throw new ApiException(400, "Missing required parameter 'authToken' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet");

            var localVarPath = "./v1/stored-payment-methods/merchants/{merchantId}/sites/{merchantSiteId}/storedPaymentMethodId/{storedPaymentMethodId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (merchantId != null) localVarPathParams.Add("merchantId", this.Configuration.ApiClient.ParameterToString(merchantId)); // path parameter
            if (merchantSiteId != null) localVarPathParams.Add("merchantSiteId", this.Configuration.ApiClient.ParameterToString(merchantSiteId)); // path parameter
            if (storedPaymentMethodId != null) localVarPathParams.Add("storedPaymentMethodId", this.Configuration.ApiClient.ParameterToString(storedPaymentMethodId)); // path parameter
            if (authToken != null) localVarHeaderParams.Add("authToken", this.Configuration.ApiClient.ParameterToString(authToken)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StoredPaymentMethodResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StoredPaymentMethodResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StoredPaymentMethodResponse)));
        }

        /// <summary>
        /// Gets a stored payment method Gets the stored payment method by its unique identifier.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="merchantSiteId"></param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of StoredPaymentMethodResponse</returns>
        public async System.Threading.Tasks.Task<StoredPaymentMethodResponse> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGetAsync (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken)
        {
             ApiResponse<StoredPaymentMethodResponse> localVarResponse = await V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGetAsyncWithHttpInfo(merchantId, merchantSiteId, storedPaymentMethodId, authToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a stored payment method Gets the stored payment method by its unique identifier.
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="merchantSiteId"></param>
        /// <param name="storedPaymentMethodId">The stored payment method identifier.</param>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <returns>Task of ApiResponse (StoredPaymentMethodResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StoredPaymentMethodResponse>> V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGetAsyncWithHttpInfo (int? merchantId, string merchantSiteId, string storedPaymentMethodId, string authToken)
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new ApiException(400, "Missing required parameter 'merchantId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet");
            // verify the required parameter 'merchantSiteId' is set
            if (merchantSiteId == null)
                throw new ApiException(400, "Missing required parameter 'merchantSiteId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet");
            // verify the required parameter 'storedPaymentMethodId' is set
            if (storedPaymentMethodId == null)
                throw new ApiException(400, "Missing required parameter 'storedPaymentMethodId' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet");
            // verify the required parameter 'authToken' is set
            if (authToken == null)
                throw new ApiException(400, "Missing required parameter 'authToken' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet");

            var localVarPath = "./v1/stored-payment-methods/merchants/{merchantId}/sites/{merchantSiteId}/storedPaymentMethodId/{storedPaymentMethodId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (merchantId != null) localVarPathParams.Add("merchantId", this.Configuration.ApiClient.ParameterToString(merchantId)); // path parameter
            if (merchantSiteId != null) localVarPathParams.Add("merchantSiteId", this.Configuration.ApiClient.ParameterToString(merchantSiteId)); // path parameter
            if (storedPaymentMethodId != null) localVarPathParams.Add("storedPaymentMethodId", this.Configuration.ApiClient.ParameterToString(storedPaymentMethodId)); // path parameter
            if (authToken != null) localVarHeaderParams.Add("authToken", this.Configuration.ApiClient.ParameterToString(authToken)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StoredPaymentMethodResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StoredPaymentMethodResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StoredPaymentMethodResponse)));
        }

        /// <summary>
        /// Stores a new payment method. 
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <param name="storedPaymentMethodRequest">The payment method to store. (optional)</param>
        /// <returns>string</returns>
        public string V1StoredPaymentMethodsPost (string authToken, StoredPaymentMethodRequest storedPaymentMethodRequest = null)
        {
             ApiResponse<string> localVarResponse = V1StoredPaymentMethodsPostWithHttpInfo(authToken, storedPaymentMethodRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Stores a new payment method. 
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <param name="storedPaymentMethodRequest">The payment method to store. (optional)</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > V1StoredPaymentMethodsPostWithHttpInfo (string authToken, StoredPaymentMethodRequest storedPaymentMethodRequest = null)
        {
            // verify the required parameter 'authToken' is set
            if (authToken == null)
                throw new ApiException(400, "Missing required parameter 'authToken' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsPost");

            var localVarPath = "./v1/stored-payment-methods";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authToken != null) localVarHeaderParams.Add("authToken", this.Configuration.ApiClient.ParameterToString(authToken)); // header parameter
            if (storedPaymentMethodRequest != null && storedPaymentMethodRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(storedPaymentMethodRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = storedPaymentMethodRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1StoredPaymentMethodsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Stores a new payment method. 
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <param name="storedPaymentMethodRequest">The payment method to store. (optional)</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> V1StoredPaymentMethodsPostAsync (string authToken, StoredPaymentMethodRequest storedPaymentMethodRequest = null)
        {
             ApiResponse<string> localVarResponse = await V1StoredPaymentMethodsPostAsyncWithHttpInfo(authToken, storedPaymentMethodRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Stores a new payment method. 
        /// </summary>
        /// <exception cref="pachirapay.Connector.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authToken">Gets or sets the authentication token.</param>
        /// <param name="storedPaymentMethodRequest">The payment method to store. (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> V1StoredPaymentMethodsPostAsyncWithHttpInfo (string authToken, StoredPaymentMethodRequest storedPaymentMethodRequest = null)
        {
            // verify the required parameter 'authToken' is set
            if (authToken == null)
                throw new ApiException(400, "Missing required parameter 'authToken' when calling StoredPaymentMethodsApi->V1StoredPaymentMethodsPost");

            var localVarPath = "./v1/stored-payment-methods";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authToken != null) localVarHeaderParams.Add("authToken", this.Configuration.ApiClient.ParameterToString(authToken)); // header parameter
            if (storedPaymentMethodRequest != null && storedPaymentMethodRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(storedPaymentMethodRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = storedPaymentMethodRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1StoredPaymentMethodsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
