/* 
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = pachirapay.Connector.Client.OpenAPIDateConverter;

namespace pachirapay.Connector.Model
{
    /// <summary>
    /// PaymentSessionResponse
    /// </summary>
    [DataContract]
    public partial class PaymentSessionResponse :  IEquatable<PaymentSessionResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentSessionResponse" /> class.
        /// </summary>
        /// <param name="operationSucceeded">Gets or sets a value indicating whether this instance had success..</param>
        /// <param name="paymentSessionId">Gets or sets the payment session identifier..</param>
        /// <param name="paymentSessionUrl">Gets or sets the payment session URL..</param>
        /// <param name="responseMessage">The global response message.</param>
        public PaymentSessionResponse(bool? operationSucceeded = default(bool?), string paymentSessionId = default(string), string paymentSessionUrl = default(string), string responseMessage = default(string))
        {
            this.OperationSucceeded = operationSucceeded;
            this.PaymentSessionId = paymentSessionId;
            this.PaymentSessionUrl = paymentSessionUrl;
            this.ResponseMessage = responseMessage;
        }
        
        /// <summary>
        /// Gets or sets a value indicating whether this instance had success.
        /// </summary>
        /// <value>Gets or sets a value indicating whether this instance had success.</value>
        [DataMember(Name="operationSucceeded", EmitDefaultValue=false)]
        public bool? OperationSucceeded { get; set; }

        /// <summary>
        /// Gets or sets the payment session identifier.
        /// </summary>
        /// <value>Gets or sets the payment session identifier.</value>
        [DataMember(Name="paymentSessionId", EmitDefaultValue=false)]
        public string PaymentSessionId { get; set; }

        /// <summary>
        /// Gets or sets the payment session URL.
        /// </summary>
        /// <value>Gets or sets the payment session URL.</value>
        [DataMember(Name="paymentSessionUrl", EmitDefaultValue=false)]
        public string PaymentSessionUrl { get; set; }

        /// <summary>
        /// The global response message
        /// </summary>
        /// <value>The global response message</value>
        [DataMember(Name="responseMessage", EmitDefaultValue=false)]
        public string ResponseMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentSessionResponse {\n");
            sb.Append("  OperationSucceeded: ").Append(OperationSucceeded).Append("\n");
            sb.Append("  PaymentSessionId: ").Append(PaymentSessionId).Append("\n");
            sb.Append("  PaymentSessionUrl: ").Append(PaymentSessionUrl).Append("\n");
            sb.Append("  ResponseMessage: ").Append(ResponseMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentSessionResponse);
        }

        /// <summary>
        /// Returns true if PaymentSessionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentSessionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentSessionResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OperationSucceeded == input.OperationSucceeded ||
                    (this.OperationSucceeded != null &&
                    this.OperationSucceeded.Equals(input.OperationSucceeded))
                ) && 
                (
                    this.PaymentSessionId == input.PaymentSessionId ||
                    (this.PaymentSessionId != null &&
                    this.PaymentSessionId.Equals(input.PaymentSessionId))
                ) && 
                (
                    this.PaymentSessionUrl == input.PaymentSessionUrl ||
                    (this.PaymentSessionUrl != null &&
                    this.PaymentSessionUrl.Equals(input.PaymentSessionUrl))
                ) && 
                (
                    this.ResponseMessage == input.ResponseMessage ||
                    (this.ResponseMessage != null &&
                    this.ResponseMessage.Equals(input.ResponseMessage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OperationSucceeded != null)
                    hashCode = hashCode * 59 + this.OperationSucceeded.GetHashCode();
                if (this.PaymentSessionId != null)
                    hashCode = hashCode * 59 + this.PaymentSessionId.GetHashCode();
                if (this.PaymentSessionUrl != null)
                    hashCode = hashCode * 59 + this.PaymentSessionUrl.GetHashCode();
                if (this.ResponseMessage != null)
                    hashCode = hashCode * 59 + this.ResponseMessage.GetHashCode();
                return hashCode;
            }
        }
    }

}
